// frontend-react/src/App.jsx
import { useEffect, useState } from 'react'
import './App.css'
import Header from './Header'

function App() {
  const [apiResponse, setApiResponse] = useState(null)
  const [apiHeaders, setApiHeaders] = useState(null)
  const [apiUrl, setApiUrl] = useState('https://jsonplaceholder.typicode.com/users/1')

  async function fetchData() {
    try{
      const response = await fetch(apiUrl)
      const data = await response.json()
      setApiResponse(data)
      setApiHeaders(response.headers)
    } catch (error) {
      console.error('Error fetching data', error)
      setApiResponse(error)
      setApiHeaders(null)
    }
  }

  useEffect(() => {
    console.log('App component mounted')
    fetchData()
  }, [])

  return (
    <>
      <Header />
      <label htmlFor='api-url'>API URL</label>
      <form className='api-url-input' onSubmit={(formSubmittedEvent) => {
        formSubmittedEvent.preventDefault()
        fetchData()
      }}>
        <input
          value={apiUrl}
          onChange={(e) => setApiUrl(e.target.value)}
          placeholder='Enter API URL'
          type='text'
        />
      <button onClick={fetchData}>Fetch Data</button>
    </form>
      <div style={{
        width: '100%',
        textAlign: 'center',
        marginTop: '1rem'
      }}>
        Try changing the url that we request 👆
      </div>
      <div className='container'>
        <h2>API Response Data (Body)</h2>
       {apiResponse && <pre>{JSON.stringify(apiResponse, null, 2)}</pre>}
        <h2>API Response Headers</h2>
        {apiHeaders && <pre>{JSON.stringify([...apiHeaders], null, 2)}</pre>}
      </div>
    </>
  )
}
export default App

// frontend-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'frontend-angular';

  apiResponse: any = null;
  apiHeaders: any = null;
  apiUrl: string = 'https://jsonplaceholder.typicode.com/users/1';

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    console.log('App component initialized');
    this.fetchData();
  }

  async fetchData() {
    try {
      const response: any = await this.http.get(this.apiUrl, { observe: 'response' }).toPromise();
      console.log(response);
      this.apiResponse = response.body;
      this.apiHeaders = response.headers;
    } catch (error) {
      console.error('Error fetching data:', error);
      this.apiResponse = error
      this.apiHeaders = null;
    }
  }

  onSubmit(form: any) {
    form.preventDefault();
    this.fetchData();
  }
}

<app-header></app-header>

<label for="api-url">API URL</label>
<form (submit)="onSubmit($event)" class='api-url-input'>
  <input [(ngModel)]="apiUrl" placeholder="Enter API URL" type="text" name="apiUrl">
  <button type="submit">Fetch Data</button>
</form>

<div style="width: 100%; text-align: center; margin-top: 1rem;">
  Try changing the url that we request 👆
</div>

<div class="container">
  <h2>API Response Data (Body)</h2>
  <pre>{{ apiResponse | json }}</pre>
  <h2>API Response Headers</h2>
  <pre>{{ apiHeaders | json }}</pre>
</div>


<router-outlet></router-outlet>
